moves-rwth/storm

.github/workflows/buildtest.yml
It can be schedueled later after testing that the workflow works with the secrets, etc.
I can also change the name of course.
=> Implement manually triggered github actions CI

.github/workflows/buildtest.yml
Fixes pull requests building the master branch
=> Github Actions: use current ref instead of hardcoded master

.github/workflows/buildtest.yml, resources/3rdparty/CMakeLists.txt, resources/3rdparty/sylvan/src/storm_wrapper.cpp, src/storm-pars/analysis/AssumptionChecker.cpp, src/storm-pars/analysis/MonotonicityHelper.cpp, src/storm-pars/modelchecker/region/SparseDtmcParameterLiftingModelChecker.cpp, src/storm-pomdp/analysis/WinningRegion.cpp, src/storm-pomdp/generator/NondeterministicBeliefTracker.cpp, src/storm-pomdp/storage/BeliefManager.cpp, src/storm-pomdp/storage/BeliefManager.h, src/storm/modelchecker/prctl/helper/SparseMdpPrctlHelper.cpp, src/storm/storage/geometry/ReduceVertexCloud.cpp, src/test/storm/modelchecker/prctl/mdp/QuantileQueryTest.cpp, src/test/storm/modelchecker/prctl/mdp/SchedulerGenerationMdpPrctlModelCheckerTest.cpp
Reduces CI tests for debian and older versions of ubuntu to only test in release mode.
Adds a new Indepth test job that tests all variations of GMP/CLN exact arithmetic and rational functions.
This PR also include fixes so that the configurations can be compiled and successfully tested.
=> Fix and Test GMP/CLN configurations

src/storm-pomdp/transformer/MakePOMDPCanonic.cpp
=> fixed #164

src/storm-dft/api/storm-dft.h, src/storm-dft/builder/ExplicitDFTModelBuilder.cpp, src/storm-dft/modelchecker/dft/DFTModelChecker.cpp, src/storm-dft/modelchecker/dft/DFTModularizer.cpp, src/storm-dft/modelchecker/dft/DFTModularizer.h, src/storm-dft/modelchecker/dft/SFTBDDChecker.cpp, src/storm-dft/modelchecker/dft/SFTBDDChecker.h, src/storm-dft/modelchecker/dft/SFTBDDPropertyFormulaAdapter.h, src/storm-dft/storage/dft/DFT.h, src/storm-dft/transformations/DftTransformator.cpp, src/storm-dft/transformations/SftToBddTransformator.h
The commits in this PR also makes small housekeeping changes.
=> Fix DFTModularizer

src/storm-pars/api/region.h, src/test/storm-pars/modelchecker/SparseDtmcParameterLiftingMonotoniciyTest.cpp
... useful for applying PLA on models that are sound by construction (via the API)
=> added a flag that disables checking the preconditions

src/storm-parsers/parser/DirectEncodingParser.cpp
Made DRN parsing more robust with better and more error messages and being less reliant on tabs vs spaces.
=> more robust parsing for DRN files

resources/cmake/find_modules/FindGUROBI.cmake
There was actually a break in the pattern ;-)
=> update GUROBI versions supported

src/storm/modelchecker/multiobjective/preprocessing/SparseMultiObjectivePreprocessor.cpp
=> multiobjective: Fixed properly dealing with unnamed reward models

CMakeLists.txt
Export whether storm was compiled with gurobi and spot
=> export variables for usage in dependent projects

src/storm-dft/parser/DFTGalileoParser.cpp
Fixes compilation in some cases
=> Added missing include.

src/test/storm/solver/GlpkLpSolverTest.cpp, src/test/storm/solver/GurobiLpSolverTest.cpp, src/test/storm/solver/Z3LpSolverTest.cpp
Fixes compilation of `GurobiLpSolverTest`.
=> Use LpFactories in solver tests.

_posts/2022-06-11-10_years.md, _posts/2022-07-31-version.1.7.0.md
- Added news about version 1.7.0
- Added news about 10 years of Storm
=> Update news on website

src/storm-pars/derivative/GradientDescentInstantiationSearcher.cpp
fixes compilation if cln is not installed
=> Remove unnecessary cln includes

_posts/2022-08-02-uaitutorial.md
We may also want to update the tutorial tab on the webpage, but I have no good idea how to do this in the best way.
=> Tutorial at UAI news

documentation/obtain-storm/dependencies.md
Forgot one mentioning of Boost version in PR #280
=> Removed another mentioning of old Boost version

_bibliography/references.bib, benchmarks.md
- Updated information on Storm STTT paper (also see https://github.com/moves-rwth/stormpy/issues/97)
- Added some own papers using Storm as backend
=> Added some references to bibliography

README.md, doc/developers.md
Started on creating some general information for developers. The idea is to (1) help new developers get faster into the code, and (2) make some development policies we follow explicit.
=> Added information for developers

src/storm/solver/GurobiLpSolver.cpp
Small fix that prevents potential memory leaks.
=> Gurobi: Fixed Typo in preprocessor directive

resources/3rdparty/CMakeLists.txt, src/storm-dft/api/storm-dft.cpp, src/storm-dft/api/storm-dft.h, src/storm-dft/storage/DftJsonExporter.cpp
- export field 'parameters' only if needed
- fixed tiny typo
=> Dft JSON parameters

resources/cmake/find_modules/FindGUROBI.cmake
Update the findGurobi script to new gurobi version 10.
=> Find Gurobi 10

documentation/obtain-storm/docker.md
Some users might want to keep the changes.
=> Mention how to keep Docker container

src/storm-pomdp/analysis/IterativePolicySearch.cpp, src/storm-pomdp/analysis/IterativePolicySearch.h, src/storm-pomdp/analysis/QualitativeAnalysisOnGraphs.cpp
Fix of a fix i made last spring :-)
=> Pomdp almsure fix

resources/3rdparty/modernjson/src/json.hpp, src/storm/adapters/RationalFunctionAdapter.h, src/storm/adapters/RationalFunctionAdapter_Private.cpp, src/storm/adapters/RationalFunctionForward.h, src/storm/modelchecker/results/ExplicitQualitativeCheckResult.h, src/storm/modelchecker/results/ExplicitQuantitativeCheckResult.cpp, src/storm/modelchecker/results/ExplicitQuantitativeCheckResult.h, src/storm/models/sparse/StandardRewardModel.h, src/storm/storage/expressions/BinaryNumericalFunctionExpression.cpp
fix for #343 …only was enabled by recent update to carl 14.24
=> fix for mistake in #343

_bibliography/references.bib
I boldly added some of the paper I co-authored. Currently they are all prototypes using storm, although I am working on integration of some things
=> Some missing papers

.github/workflows/buildtest.yml, CMakeLists.txt, src/storm/modelchecker/lexicographic/spotHelper/spotProduct.cpp, src/storm/models/ModelBase.cpp
- use `storm-basesystem:latest` for latest Ubuntu version (23.04)
=> Updated CI

resources/3rdparty/CMakeLists.txt
Based on a recent bug report via email
=> Better error message for carl version mismatch

src/storm/modelchecker/lexicographic/spotHelper/spotProduct.cpp
Fixes compilation on recent macOS.
=> Added missing include

src/storm-pomdp-cli/storm-pomdp.cpp, src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.cpp
Small changes to the output for Storm-POMDP.
=> Adjusted POMDP output text

CHANGELOG.md
=> Added storm-pomdp changes to CHANGELOG.md

CHANGELOG.md, resources/3rdparty/CMakeLists.txt
Ensure compatibility with [carl-storm](https://github.com/moves-rwth/carl-storm)
=> Increased CARL_MINVERSION to 14.23

documentation/obtain-storm/docker.md
- `travis` is not used anymore
=> Website: updated Docker image names

.github/workflows/buildtest.yml, CMakeLists.txt, resources/3rdparty/CMakeLists.txt, resources/doxygen/CMakeLists.txt
=> Increased CMake version to 3.15

documentation/obtain-storm/build.md, documentation/obtain-storm/dependencies.md
Updated documentation after https://github.com/moves-rwth/storm/pull/393
=> Website: Debian 10 is not supported anymore

.github/workflows/Dockerfile.archlinux, .github/workflows/Dockerfile.carl_implicit, .github/workflows/buildtest.yml, Dockerfile
- Updated `Dockerfile` to accept arguments
- Major revision of CI which now builds upon the existing Dockerfile. This should simplify the CI workflow.
- Added two Dockerfiles for CI:
* `Dockerfile.archlinux` for building on the latest Archlinux version. This allows to test with the latest compiler and library versions.
* `Dockerfile.carl_implicit` for implicitly building Carl-storm from within Storm
=> Dockerfile in CI

src/storm/storage/BitVector.cpp, src/storm/storage/BitVector.h, src/test/storm/storage/BitVectorTest.cpp
Also use builtin functions to find correct bit indices more efficiently.
=> BitVector: added support for reverse iteration

src/storm/modelchecker/multiobjective/pcaa/StandardPcaaWeightVectorChecker.cpp
Fixes an issue where sub-optimal schedulers were generated.
=> Fix for multi-objective model checking

resources/3rdparty/cudd-3.0.0/Makefile.am
Fixes https://github.com/moves-rwth/storm/issues/388
=> do not compile CUDD docs

.github/workflows/Dockerfile.archlinux, .github/workflows/Dockerfile.indepth, .github/workflows/buildtest.yml, Dockerfile
Resolves https://github.com/moves-rwth/storm/issues/433
=> CI: Build with MathSAT 5 for indepth tests

src/storm-parsers/parser/FormulaParserGrammar.cpp, src/storm-parsers/parser/FormulaParserGrammar.h, src/storm/logic/PlayerCoalition.cpp, src/storm/logic/PlayerCoalition.h, src/storm/models/sparse/Smg.cpp, src/storm/storage/PlayerIndex.h
Boost variant replaced by std variant
=> playercoalition: boost variant to std variant

src/storm-counterexamples/counterexamples/MILPMinimalLabelSetGenerator.h, src/storm-counterexamples/counterexamples/SMTMinimalLabelSetGenerator.h, src/storm-pars/analysis/OrderExtender.cpp, src/storm-pars/derivative/GradientDescentInstantiationSearcher.cpp, src/storm-pars/derivative/GradientDescentInstantiationSearcher.h, src/storm-pars/derivative/SparseDerivativeInstantiationModelChecker.cpp, src/storm-pars/modelchecker/instantiation/SparseCtmcInstantiationModelChecker.cpp, src/storm-pars/modelchecker/instantiation/SparseDtmcInstantiationModelChecker.cpp, src/storm-pars/modelchecker/instantiation/SparseMdpInstantiationModelChecker.cpp, src/storm-pars/modelchecker/region/RegionModelChecker.cpp, src/storm-pars/utility/ModelInstantiator.cpp, src/storm-pars/utility/parametric.cpp, src/storm-pars/utility/parametric.h, src/storm-parsers/api/storm-parsers.h, src/storm-parsers/parser/DirectEncodingParser.cpp, src/storm/builder/ExplicitModelBuilder.cpp, src/storm/generator/TransientVariableInformation.h, src/storm/modelchecker/AbstractModelChecker.h, src/storm/utility/Engine.cpp, src/test/storm-pars/analysis/OrderExtenderTest.cpp, src/test/storm-pars/modelchecker/ParametricDtmcPrctlModelCheckerTest.cpp
Mostly issues to reduce what code depends on settings and based on analysis of compilation times. 
Also added a couple of missing std's
=> various improvements on the inclusion structure

_layouts/home.html, documentation/background/languages.md, documentation/usage/running-storm.md
Updated documentation after https://github.com/moves-rwth/storm/pull/456
=> Removed documentation on pGCL as support was removed

.github/workflows/doxygen.yml
Use image `carl-storm` instead of `carl`.
=> Doxygen CI was using old Docker image

src/storm-gamebased-ar/abstraction/jani/EdgeAbstractor.cpp, src/storm-gamebased-ar/abstraction/prism/CommandAbstractor.cpp, src/storm-pars/analysis/Order.cpp, src/storm-pars/transformer/ParameterLifter.cpp, src/storm-parsers/parser/AtomicPropositionLabelingParser.cpp, src/storm/solver/GurobiLpSolver.cpp, src/storm/storage/dd/sylvan/InternalSylvanAdd.cpp
=> fix warnings

resources/3rdparty/cpphoafparser-0.99.2/include/cpphoafparser/util/dynamic_bitset.hh
=> fix operator (bitwise vs logical)

src/storm/storage/expressions/ExpressionManager.cpp
There was no diff between the aux and non-aux code here.
=> remove if/else with duplicate code

.github/workflows/buildtest.yml, .github/workflows/doxygen.yml, .github/workflows/formatapply.yml, .github/workflows/formatcheck.yml
Updated a couple of Github actions to the latest version.
=> CI: bumped Github action versions

src/storm/storage/BitVector.cpp, src/storm/storage/dd/cudd/CuddAddIterator.cpp
see https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first
=> no nullpointer check necessary before free/delete[]

.github/workflows/release_docker.yml, doc/checklist_new_release.md
Add Github Action which builds and deploy Docker images for a given tag (e.g. `1.2.3` or `stable`).
=> CI to create Docker releases

src/storm/storage/SparseMatrix.cpp, src/storm/storage/SparseMatrix.h, src/test/storm/storage/SparseMatrixTest.cpp
Assertion was violated for empty matrix.
=> Fix assertion in SparseMatrix

.github/workflows/Dockerfile.doxygen, .github/workflows/doxygen.yml
Also fixes the current CI build issue for the documentation
=> Dedicated Dockerfile for buiding Doxygen documentation

src/test/storm-gamebased-ar/abstraction/GraphTest.cpp, src/test/storm-gamebased-ar/abstraction/PrismMenuGameTest.cpp, src/test/storm-gamebased-ar/modelchecker/abstraction/GameBasedDtmcModelCheckerTest.cpp, src/test/storm-gamebased-ar/modelchecker/abstraction/GameBasedMdpModelCheckerTest.cpp, src/test/storm/builder/DdJaniModelBuilderTest.cpp, src/test/storm/builder/DdPrismModelBuilderTest.cpp, src/test/storm/solver/FullySymbolicGameSolverTest.cpp, src/test/storm/storage/DdTest.cpp, src/test/storm/storage/SylvanDdTest.cpp, src/test/storm/storage/SymbolicBisimulationDecompositionTest.cpp, src/test/storm/utility/GraphTest.cpp
Introduced parametrized tests for CUDD and Sylvan, and reduced code duplication.
=> Merged CUDD and Sylvan tests

src/storm/storage/sparse/StateValuations.cpp
Added assertions to check the variable types.
Was raised in https://github.com/moves-rwth/stormpy/issues/210
=> Assertions with type check for variables

src/test/storm/modelchecker/lexicographic/LexicographicModelCheckingTest.cpp
=> Added check that Z3 is available in test

resources/3rdparty/carl/CMakeLists.txt, resources/3rdparty/googletest/CMakeLists.txt, resources/3rdparty/googletest/googlemock/CMakeLists.txt, resources/3rdparty/googletest/googletest/CMakeLists.txt
=> Bump cmake_minimum_required version for carlext

src/storm/storage/BitVectorHashMap.cpp, src/storm/storage/BitVectorHashMap.h, src/storm/storage/MaximalEndComponent.cpp, src/storm/storage/MaximalEndComponent.h, src/storm/storage/expressions/ExpressionManager.cpp, src/storm/storage/expressions/ExpressionManager.h, src/storm/storage/sparse/StateValuations.cpp, src/storm/storage/sparse/StateValuations.h
Fixes some compile warning under AppleClang.
=> Added const qualifier to operator==

src/storm/settings/modules/MinMaxEquationSolverSettings.cpp, src/storm/settings/modules/NativeEquationSolverSettings.cpp, src/storm/settings/modules/TopologicalEquationSolverSettings.cpp, src/storm/solver/IterativeMinMaxLinearEquationSolver.cpp, src/storm/solver/IterativeMinMaxLinearEquationSolver.h, src/storm/solver/MinMaxLinearEquationSolver.cpp, src/storm/solver/NativeLinearEquationSolver.cpp, src/storm/solver/NativeLinearEquationSolver.h, src/storm/solver/SolverSelectionOptions.cpp, src/storm/solver/SolverSelectionOptions.h, src/storm/solver/helper/GuessingValueIterationHelper.cpp, src/storm/solver/helper/GuessingValueIterationHelper.h, src/test/storm/modelchecker/prctl/dtmc/DtmcPrctlModelCheckerTest.cpp, src/test/storm/modelchecker/prctl/mdp/MdpPrctlModelCheckerTest.cpp, src/test/storm/solver/LinearEquationSolverTest.cpp, src/test/storm/solver/MinMaxLinearEquationSolverTest.cpp
Implementing the algorithm proposed in https://arxiv.org/abs/2505.06769.
=> Implement Guessing Value Iteration

.github/workflows/Dockerfile.archlinux, .github/workflows/Dockerfile.release, CMakeLists.txt, Dockerfile
Auto-generated pull request triggered by a new carl-storm version.
- Manually close and reopen this PR to trigger the CI.
=> Update carl-storm 14.32.1

.github/workflows/Dockerfile.alpine, .github/workflows/Dockerfile.archlinux, .github/workflows/Dockerfile.release, Dockerfile
Manual update needed because automatic script is not robust enough for `14.32.1`.
=> Update carl-storm version to 14.33

CMakeLists.txt, doc/checklist_new_release.md, resources/3rdparty/CMakeLists.txt
and forgot to update carl version in one place
=> Removed unused Carl CMake variables
