- src/storm/api/properties.cpp
Before, the argument to `--prop` was only treated as a file if (a) it exits and (b) contains a dot.
We remove the requirement for a dot and always treat the argument as a file if it exists.
Fixes #25.
> Simplify check whether argument of --prop is a file/property

- src/storm-cli-utilities/cli.cpp
- src/storm-cli-utilities/cli.h
- src/storm/api/properties.cpp
With our talent of stumbling onto corner cases, we had the situation where due to some bogus scripting `storm` was called with
`--prop properties.props ''`
i.e., an empty filter, resulting in no output for properties, as all of the properties were filtered away. This was quite difficult to debug, as the
`Command line arguments: ...`
line in the log does not quote the arguments, rendering the empty filter quite invisible.
In this PR, we propose:
- quote the command line arguments in the log if they contain unsafe characters (or are empty)
- print a warning if the filter is empty and thus all properties are filtered away.
> Quote command-line arguments, warn on empty filter

- src/storm/modelchecker/AbstractModelChecker.cpp
- src/storm/modelchecker/AbstractModelChecker.h
Currently, in the error messages thrown by the AbstractModelChecker base class, the concrete derived class is not apparent.
This PR adds a getClassName() method that provides the class name of a derived model checker class (via RTTI and Boost-based demangling) and uses that in the error messages:
```
ERROR (AbstractModelChecker.cpp:41):
The model checker (storm::modelchecker::SparseDtmcPrctlModelChecker<storm::models::sparse::Dtmc<double, storm::models::sparse::StandardRewardModel<double> > >) is not able to check the formula ...
```
This should give the user at least some hints what might be going on.
> AbstractModelChecker: improve error messages

- resources/3rdparty/nix-scripts/README
- resources/3rdparty/nix-scripts/carl/default.nix
- resources/3rdparty/nix-scripts/carl/gtest.cmake
- resources/3rdparty/nix-scripts/default.nix
- resources/3rdparty/nix-scripts/googletest/default.nix
- resources/3rdparty/nix-scripts/l3pp/default.nix
- resources/3rdparty/nix-scripts/mathsat/default.nix
- resources/3rdparty/nix-scripts/storm-checker/default.nix
- resources/3rdparty/nix-scripts/z3/default.nix
This PR adds [Nix](https://nixos.org) build scripts that build storm and all its dependencies as a Nixpkgs overlay.
I use it to run specific versions of storm on a modelchecking test farm that is driven by [Hydra](https://nixos.org/hydra), a CI based on Nix.
The overlay is self-contained and does not alter the storm build system. Although, it's build scripts do alter the build system to extract external cmake projects into separate libraries, as the Nix build system does not allow network access during build time. Thus, build dependencies cannot be downloaded on the fly. The advantage is, that a different storm builds make use of shared dependencies.
> Nix integration

- .github/workflows/buildtest.yml
- .github/workflows/doxygen.yml
This workflow needs the secret `DOC_DEPLOY_KEY` (an ssh key, like in the documatation of [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages)) to function correctly.
Its needed to push the documentation to an external repo.
This pull request also fixes a typo in buildtest.yml.
The workflow is meant to run on every push, that would be
```
on:
push:
branches:
- master
```
> Implement manually triggered github actions CI

- .github/workflows/buildtest.yml
- .github/workflows/doxygen.yml
Following the suggestion in moves-rwth/storm#108, we only execute the actions for deployment and doxygen on the main repo (and not on the forks).
> Github Actions: only run doxygen and deploy on master branch of original repo

- src/storm-dft/api/storm-dft.h
- src/storm-dft/modelchecker/dft/DFTModelChecker.h
- src/storm-dft/utility/RelevantEvents.h
Instead use a flexible iterator based api that is independent of a container.
Also make RelevantEvents more easily mutable to add new events.
> Make RelevantEvents independent of std::vector

- CHANGELOG.md
- resources/examples/testfiles/mdp/unbounded.nm
- src/storm-counterexamples/counterexamples/SMTMinimalLabelSetGenerator.h
- src/storm-parsers/parser/PrismParser.cpp
- src/storm-parsers/parser/PrismParser.h
- src/storm/builder/DdPrismModelBuilder.cpp
- src/storm/generator/PrismNextStateGenerator.cpp
- src/storm/generator/VariableInformation.cpp
- src/storm/generator/VariableInformation.h
- src/storm/storage/jani/UnboundedIntegerVariable.cpp
- src/storm/storage/jani/UnboundedIntegerVariable.h
- src/storm/storage/prism/IntegerVariable.cpp
- src/storm/storage/prism/IntegerVariable.h
- src/storm/storage/prism/Module.cpp
- src/storm/storage/prism/Module.h
- src/storm/storage/prism/Program.cpp
- src/storm/storage/prism/Program.h
- src/storm/storage/prism/ToJaniConverter.cpp
- src/test/storm/builder/DdPrismModelBuilderTest.cpp
- src/test/storm/builder/ExplicitPrismModelBuilderTest.cpp
- src/test/storm/parser/PrismParserTest.cpp
- src/test/storm/storage/PrismProgramTest.cpp
This PR adds support for PRISM programs that use unbounded integer variables declared via `x : int`.
See also the [PRISM documentation](https://www.prismmodelchecker.org/manual/ThePRISMLanguage/ModulesAndVariables) and the [hill-toggle](https://qcomp.org/benchmarks/#hill-toggle) and [p53](https://qcomp.org/benchmarks/#p53) benchmarks at QComp.
The explicit model builder (sparse engine) supports building such models assuming that they are finite. The `--int-bits <NUMBER>` setting can be used to specify how many bits shall be reserved for these variables.
The symbolic model builder will error for these models.
> Support for Prism Programs with unbounded integers

- resources/3rdparty/include_cudd.cmake
After updating the XCode CLT, the problem described in issue moves-rwth#104 occurs again as the shipped AppleClang version (12.0.5.12050022) does not fix the underlying issue. Changing the condition from "equal" to "greater or equal" reestablishes the fix.
> Fix for CUDD

- src/storm/builder/ExplicitModelBuilder.h
- src/storm/storage/Distribution.h
- src/storm/storage/DistributionWithReward.h
- src/storm/storage/bisimulation/BisimulationDecomposition.h
- src/storm/storage/bisimulation/DeterministicModelBisimulationDecomposition.h
- src/storm/storage/bisimulation/NondeterministicModelBisimulationDecomposition.h
- src/storm/utility/ConstantsComparator.cpp
- src/storm/utility/ConstantsComparator.h
**ConstantsComparator**: The old code used `abs(x-y)/abs(x+y)<= epsilon` when comparing two numbers for equality (modulo relative precision). This is weird when x and y have different signs and potentially even causes a div by 0 whenever `x=-y`. Moreover the templating was awkward, causing a lot of code duplications and a Warning with clang.
> Revised ConstantsComparator

- src/storm/storage/expressions/Expression.cpp
- src/storm/storage/expressions/Type.cpp
- src/storm/storage/expressions/Type.h
- src/test/storm/storage/ExpressionTest.cpp
This pull request fixes the type of modulo expressions if both parameters are integers. Previously, the output of `operator%(...)` was always a rational expression, while it should be an integer expression in this case. This caused an error when reading prism files using the modulo operator with integer variables.
I also changed modulo(...), which already returned the correct type, but confusingly used the `minimumMaximum(...)` function for this.
> Fixed incorrect type of modulo expression with integer inputs

- src/storm/storage/sparse/StateValuations.cpp
POMDP observation valuations have labelVariables that are now supported in the export to JSON. I also updated the error message to facilitate debugging in the future.
> toJson supports labelValues

- src/storm-parsers/parser/ConstantDataType.cpp
- src/storm-parsers/parser/ConstantDataType.h
- src/storm-parsers/parser/FormulaParserGrammar.h
- src/storm/logic/FormulaContext.cpp
- src/storm/logic/FormulaContext.h
With the following
``` cpp
// Enable the following lines to print debug output for most the rules.
debug(start);
debug(constantDefinition);
debug(stateFormula);
...
```
we are able to print debug outputs for formula parsing. This lacked the two `ostream` operators added with this PR.
> Fix FormulaParser Debug 

- CHANGELOG.md
- src/storm-cli-utilities/model-handling.h
- src/storm/api/export.h
- src/storm/io/ModelExportFormat.cpp
- src/storm/io/ModelExportFormat.h
- src/storm/models/sparse/Model.cpp
- src/storm/models/sparse/Model.h
- src/storm/settings/modules/IOSettings.cpp
- src/storm/settings/modules/IOSettings.h
New option `--exportbuild` exports the state space of the model in various formats: `.ddrd`, `.drn`, `.dot`, and a new `.json` format.
The json export includes transition probabilities, labels, rewards, exit rates, as well as (if included during model building) state valuations, choice labels, and choice origins.
For example, `storm -qvbs stream 0 ""  --exportjson test.json --buildstateval --buildchoiceorig --buildfull --build-all-labels --exact` yields
```json
[
{
"c": [
{
"id": 0,
"origin": {
"action-label": "buffer",
"transitions": [
{
"action": "buffer",
"automaton": "streamingclient",
"destinations": [
{
"assignments": [
{
"comment": "s <- 1",
"ref": "s",
"value": 1
}
],
"location": "l"
}
],
"guard": {
"comment": "(((s = 0) & (n < 10)) & (k = n))",
"exp": {
"left": {
"left": { …
```
> Added model export in .json.

- resources/3rdparty/CMakeLists.txt
- resources/3rdparty/patches/eigen.patch
Reverts moves-rwth/storm#153
There seem to be some issues with gcc11 and the `GMRES` method in Eigen 3.4.0. The old Eigen version worked fine in this regard but had issues with `-DSTORM_USE_CLN_EA=On`.
However, since the issues with the new version affect the *default* CMAKE configuration, I think it's best to go back to the old version for now.
I'll add an issue addressing this for future reference.
> Revert "Update Eigen to 3.4.0"

- resources/examples/testfiles/mdp/enumerate_init.jani
- resources/examples/testfiles/mdp/enumerate_init.prism
- src/storm/generator/CompressedState.cpp
- src/storm/generator/JaniNextStateGenerator.cpp
- src/storm/generator/PrismNextStateGenerator.cpp
- src/storm/utility/combinatorics.h
- src/test/storm/builder/ExplicitJaniModelBuilderTest.cpp
- src/test/storm/builder/ExplicitPrismModelBuilderTest.cpp
Revises enumeration of initial states in Prism and Jani NextStateGenerators.
FYI: The brute-force enumeration of all initial states is triggered whenever every (valid) variable valuation is initial, i.e., if no (non-transient) variable has an initial value and all initial restrictions are `true`.
Apparently, this enumeration was quite broken.
This PR fixes issues with models that contain
- boolean variables, 
- integer variables, where the lower bound is not zero, and
- initial locations other than 0.
There was also an issue with converting `CompressedState`s with negative integer assignments to a string.
> Fix init state enumeration

- src/storm/modelchecker/prctl/helper/SparseMdpEndComponentInformation.cpp
- src/storm/storage/MaximalEndComponentDecomposition.cpp
- Fixed an issue with subsystem MEC decomposition (fixes #167)
The issue happened when there is a choice within the subsystem that leads outside of the subsystem. In the old version, such a choice could contribute to an End Component (simply ignoring transitions that lead to non-subsystem states)
Issue #167 was triggered by the fact that two ECs were considered as one single EC.
- Fixed setting arbitrary scheduler choices for non-MaybeStates
> Fixes related to End Components and Scheduler Extraction

- CHANGELOG.md
- resources/3rdparty/modernjson/src/json.hpp
- resources/examples/testfiles/ctmc/expvisittimes.jani
- src/storm-cli-utilities/model-handling.h
- src/storm/api/export.h
- src/storm/api/verification.h
- src/storm/modelchecker/csl/SparseCtmcCslModelChecker.cpp
- src/storm/modelchecker/csl/SparseCtmcCslModelChecker.h
- src/storm/modelchecker/helper/indefinitehorizon/visitingtimes/SparseDeterministicVisitingTimesHelper.cpp
- src/storm/modelchecker/helper/indefinitehorizon/visitingtimes/SparseDeterministicVisitingTimesHelper.h
- src/storm/modelchecker/helper/infinitehorizon/SparseDeterministicInfiniteHorizonHelper.cpp
- src/storm/modelchecker/helper/infinitehorizon/SparseInfiniteHorizonHelper.cpp
- src/storm/modelchecker/helper/infinitehorizon/SparseInfiniteHorizonHelper.h
- src/storm/modelchecker/helper/infinitehorizon/SparseNondeterministicInfiniteHorizonHelper.cpp
- src/storm/modelchecker/prctl/SparseDtmcPrctlModelChecker.cpp
- src/storm/modelchecker/prctl/SparseDtmcPrctlModelChecker.h
- src/storm/modelchecker/results/ExplicitQualitativeCheckResult.cpp
- src/storm/modelchecker/results/ExplicitQualitativeCheckResult.h
- src/storm/modelchecker/results/ExplicitQuantitativeCheckResult.cpp
- src/storm/modelchecker/results/ExplicitQuantitativeCheckResult.h
- src/storm/settings/modules/IOSettings.cpp
- src/storm/settings/modules/IOSettings.h
- src/storm/storage/StronglyConnectedComponentDecomposition.cpp
- src/storm/storage/StronglyConnectedComponentDecomposition.h
- src/test/storm/modelchecker/csl/ExpectedVisitingTimesCtmcCslModelCheckerTest.cpp
This PR adds the functionality to compute the expected times each state of a DTMC or CTMC is visited. 
In other words, the resulting value at state `s` coincides with the total reward `R{"rew_s"}=? [C]`, where the reward structure `rew_s`  only assigns reward 1 to state `s`. If `s` does not lie on a cycle, this value actually also coincides with the probability to reach `s`.
The underlying idea is to solve the infamous forward equation system (`x * P + init = x`) for each non-bottom SCC with probability matrix `P`.
States in (reachable) BSCCs always have value `inf`.
Other related stuff in here:
- Improved the `--exportresult` output to also include state labels.
- Changed the JSON output for weird floats such as `inf` or `nan`. Before, the output just said `null` in those cases but I …
> Computation of the expected number of times each state in a DTMC/CTMC is visited (sparse engine)

- resources/3rdparty/sylvan/src/sylvan_bdd_storm.h
- resources/3rdparty/sylvan/src/sylvan_mtbdd_storm.h
- src/storm/api/bisimulation.h
This PR adds some `#include`s that apparently were missing.
I discovered this when applying code formating (which also sorts `#include`s) to the code base.
> Added missing includes

- .github/workflows/buildtest.yml
Previously, ubuntu 20-10 was used which reached end of life.
We now also run our tests for debian 11, but I decided to no longer test for debian 9.
Note that the latter ships with GCC 6 which has quite limited c++17 support, so I think that we should eventually drop support for debian 9, anyway.
> Updated ubuntu base system and debian version in buildtest

- src/storm-pars/modelchecker/region/SparseParameterLiftingModelChecker.cpp
Initial bound for pla was not working correctly, I think I fixed this before but somewhere in merge it got lost. 
I now fixed it with boost optional, another option would be to either use a boolean to check if it got initialized, or correctly initialize it at 0/1 for probabilities and 0 and infty for rewards.
> Fix initial bound for pla

- resources/3rdparty/cpptemplate/cpptempl.h
- src/storm/models/Model.h
- src/storm/models/sparse/DeterministicModel.h
- src/storm/models/sparse/Dtmc.h
- src/storm/models/sparse/Mdp.h
- src/storm/models/sparse/Model.h
- src/storm/models/sparse/NondeterministicModel.h
Towards supporting an update of stormpy, these base classes are missing virtual destructors even though this is strongly recommended.
> virtual destructors added

- src/storm/storage/BitVector.cpp
- src/test/storm/storage/BitVectorTest.cpp
Currently, assigning a large BitVector to a small one causes the assignment operator to write out of bounds. This PR fixes that by making sure the `bitCount` is updated *after* we check if the two BitVectors have the same size. Note that `bucketCount()` is computed using `bitCount`. In other words, assuming buckets is not null, the condition of the if statement always false, which means that the size of the current `buckets` is never changed. This leads to OOB in the `std::copy_n` that follows. I added a simple test to check that it indeed works. The test that I added crashes without the fix.
> Fix BitVector::operator= OOB

- src/storm/modelchecker/exploration/SparseExplorationModelChecker.cpp
- src/storm/storage/Decomposition.h
- src/storm/utility/KwekMehlhorn.cpp
This PR fixes 3 cases of UB as found by running the tests while compiling with [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) (i.e. `-fsanitize=address` in gcc or clang). I've merged these changes into one commit and PR because they are relatively minor, if separate PRs are preferred that is also fine. The changes I made summarized:
* `SparseExplorationModelChecker.cpp`:
The current code retrieves the `actionBounds` by reference, which is an entry in a vector. Afterwards, the `initializeBoundsForNextAction` calls `push_back` on this vector which can make the previously obtained reference invalid. This happens when the vector needs to reallocate.
* `Decomposition.h`:
Missing virtual deconstructor of base class.
* `KwekMehlhorn.cpp`:
Using `auto` in …
> Fix UB as found by AddressSanitizer

- resources/cmake/find_modules/FindGUROBI.cmake
This adds the new Gurobi version 9.5.0 to our findGurobi.cmake
> Cmake: Find Gurobi 9.5.0

- .github/workflows/buildtest.yml
- CMakeLists.txt
Adds AddressSanitizer as build configuration option and enables it for the 'indepthTests' jobs inside the 'Build Test' workflow. See related issue #194. For now the memory leak detection is turned off while running the tests as the current code does have some memory leaks, but that is another issue.
You can see the new workflow passing at [my fork](https://github.com/Marckvdv/storm/actions/workflows/buildtest.yml).
> Add AddressSanitizer as build configuration option

- src/storm-pars/derivative/GradientDescentConstraintMethod.h
- src/storm-pars/derivative/GradientDescentInstantiationSearcher.cpp
- src/storm-pars/derivative/GradientDescentInstantiationSearcher.h
- src/storm-pars/derivative/GradientDescentMethod.h
- src/storm-pars/derivative/SparseDerivativeInstantiationModelChecker.cpp
- src/storm-pars/derivative/SparseDerivativeInstantiationModelChecker.h
- src/test/storm-pars/derivative/GradientDescentInstantiationSearcherTest.cpp
I've fixed some bugs in Gradient Descent, e.g.
- used to fail when the initial state wasn't zero
- used to fail when the formula wasn't "at some point target" (so storm-pars.cpp preprocessing), now it supports arbitrary labels and until formulas
- used to fail when there are transitions that have higher degree than one
- applied code formatting (makes the diff quite unreadable though :( )
These are all things that never hold for pMCs coming out of storm-pomdp, so I didn't catch these bugs previously.
I added a test for the first bug (applying bisimulation in a test, which results in the initial state not being zero), but not for the other ones yet - that's something I still need to do.
> Fix Gradient Descent bugs

- src/storm/modelchecker/multiobjective/deterministicScheds/DeterministicSchedsLpChecker.cpp
- src/storm/models/sparse/Model.cpp
- src/storm/models/sparse/NondeterministicModel.cpp
- src/storm/models/sparse/NondeterministicModel.h
- src/storm/transformer/SubsystemBuilder.cpp
- src/storm/transformer/SubsystemBuilder.h
- src/test/storm/modelchecker/prctl/mdp/SchedulerGenerationMdpPrctlModelCheckerTest.cpp
When applying a fully defined scheduler to an MDP, we obtain a DTMC; this allows applying DTMC-specific code on this model.
> Induced scheduler

- .clang-format-ignore
- src/storm-dft/storage/dft/DFTStateGenerationInfo.h
Enable automatic code formatting for storm-dft, storm-dft-cli and test/storm-dft.
Actual code formatting will be automatically performed by Github workflow.
New PR following the suggestions in PR #211.
> Enable automatic code formatting for storm-dft

- .github/workflows/formatapply.yml
emphasizes that the PR generated by the `apply-code-format` workflow should be merged and not rebased (cf PR #211)
> Updated description of auto PR

- src/storm/storage/SparseMatrix.cpp
Fixes https://github.com/moves-rwth/storm/issues/204.
Notice that one could further clean this function as we are now not using that only one entry is out-of-order, by either 
- only cleanup after moving to the next row
- use something like insertion sort right away
Nevertheless, I think this deserves being pulled in as it fixes an open bug in the way we discussed.
> fix handling duplicate entries in the sparse matrix builder

- .github/workflows/buildtest.yml
- Updated Github workflows to use new Ubuntu 22.04 (LTS) instead of Ubuntu 21.10
- Also build Carl without carl-parser. The parser is explicitly installed in the stormpy CI where it is needed.
> CI tests use Ubuntu 22.04

- src/storm/storage/expressions/Expression.cpp
- src/test/storm/storage/ExpressionEvalutionTest.cpp
Regarding issue #221. Correctly implements the modulo operator for expressions in accordance with Prism, by introducing an ITE for dealing with negative numbers. I added a test to check the behavior.
> Remainder -> Modulo in accordance with Prism

- src/storm/storage/BitVector.h
- src/storm/storage/expressions/ExpressionManager.h
- src/storm/utility/shortestPaths.h
`std::iterator` is deprecated since C++17. Updated it according to https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/
> Updated deprecated std::iterator

- resources/examples/testfiles/dtmc/crowds-5-5.drn
- resources/examples/testfiles/ma/jobscheduler.drn
- src/storm-parsers/parser/DirectEncodingParser.cpp
The current code throws a
```
ERROR (DirectEncodingParser.cpp:209): More actions detected than declared (in @nr_choices).
```
when parsing the very last choice, even if the `@nr_choices` hint is correct.
This PR fixes the issue.
> DRN Parser: Fix off-by-one issue

- .github/workflows/formatapply.yml
- .github/workflows/formatcheck.yml
This allows to use clang-format version 14 which is also the current version in Homebrew.
Clang-format version 14 leads to small formatting differences compared to version 12 (notably for `StandardRewardModel`).
> Updated clang-format-lint-action to version 0.14

- src/storm/storage/prism/ToJaniConverter.cpp
fixes #205
The issue was that variable declarations were not considered when finding the set of modules that access a given variable.
As a consequence, if a variable `x` is declared in a module `A` but *only* used in a different module `B`, then we assumed that only a single module accesses `x` and hence `x` was not made a global variable.
Now we also consider variable declarations, so `x` is accessed by both modules `A` and `B`.
I did consider further optimisations (like moving `x` to the scope of `B`; or even making `x` a constant since it is never written to). However, I consider this a rare edge case so I did not want to make things unnecessarily complicated.
> prism-to-jani: fixed detection of variables to make global

- resources/examples/testfiles/mdp/coin_flips.nm
- src/storm/logic/ExtractMaximalStateFormulasVisitor.cpp
- src/storm/logic/ToPrefixStringVisitor.cpp
- src/test/storm/modelchecker/prctl/mdp/MdpPrctlModelCheckerTest.cpp
With this PR, step-bounded until formulas are  supported within LTL formulas.
This is realised using a transformation to nested `X` operators. 
Unfortunately, this is the best way to do this right now, because we currently transform the formula into a prefix string that is then parsed by spot. This prefix syntax (also used by e.g. ltl2dstar) does not support step-bounds.
In principle, it would be possible to avoid the prefix string transformation and directly use the spot API (which supports at least step bounded `F` operators). However, I looked into the src of spot and it seems that they also just transform to nested `X`s.
> Allow step-bounded until formulas in LTL.

- Dockerfile
- Use `storm-basesystem:latest` as common base now. This avoids having to update the Dockerfile every time a new Ubuntu version is released.
- Added missing flag for carl
- Build with Spot
> Updated Dockerfile with Spot support

- src/storm/storage/Scheduler.cpp
- src/storm/storage/Scheduler.h
This prints an error if this is not the case, instead of segfaulting.
> Printing finite-state schedulers requires model 

- src/storm-pars/derivative/GradientDescentInstantiationSearcher.cpp
- src/storm-pars/derivative/SparseDerivativeInstantiationModelChecker.cpp
On #276 
- Revise GradientDescentInstantiationSearcher.cpp to use the macros
- Revise SparseDerivativeInstantiationModelChecker.cpp to use the macros
- Use "\n" instead of std::endl
> Replace std::cout with STORM_PRINT family of macros

- documentation/obtain-storm/dependencies.md
Raised in #279.
I opted to remove the part on manually building Boost, because all relevant distros should provide a recent enough Boost version.
> Updated documentation on Boost dependency

- src/storm-dft/storage/DftModule.cpp
- src/storm-dft/storage/DftModule.h
- src/storm-dft/utility/DftModularizer.cpp
- src/storm-dft/utility/DftModularizer.h
- src/test/storm-dft/storage/DftModuleTest.cpp
Fixed an issue with the DFT modularisation pointed out by @AhmadZafarDGB.
> Storm-dft: treat single BEs as modules

- src/storm/storage/jani/visitor/JSONExporter.cpp
The jani-to-json export produced unary minus expressions, which are not part of the [jani-spec](https://docs.google.com/document/d/1BDQIzPBtscxJFFlDUEPIo8ivKHgXT8_X6hz5quq7jK0/).
This PR changes the exports of expressions like `-x` to
```json
{ "left": 0, "op": "-",  "right": "x" }
```
> JANI to JSON export: Fixed unary minus.

- src/storm/logic/RewardAccumulation.h
- src/storm/storage/jani/traverser/RewardModelInformation.cpp
Fixed handling the case where a reward expression in a JANI property contains constants.
I also piggy-backed a fix to this warning:
```console
storm/logic/RewardAccumulation.h:10:5: warning: definition of implicit copy assignment operator for 'RewardAccumulation' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
RewardAccumulation(RewardAccumulation const& other) = default;
```
> Fixed JANI reward expressions with constants

- src/storm/storage/SparseMatrix.cpp
- src/storm/storage/SparseMatrix.h
- src/test/storm/storage/SparseMatrixTest.cpp
This PR adds a Boolean flag to all transformations in SparseMatrix that may lead to zero entries. If the flag is set, entries that are zero are deleted from the sparse matrix representation instead of just being set to zero. As in many cases, the performance impact of this operation is not desirable, the default behavior of not dropping zero entries is preserved.
This also directly exposes the default behavior and helps to prevent implicit expectations about the form of the matrix after the transformation has been applied (see also #309).
This pull request resolves #309.
> Direct elimination of zero entries in SparseMatrix transformations

- resources/3rdparty/CMakeLists.txt
Adds compile flag `DBOOST_PHOENIX_STL_TUPLE_H_` to prevent issue in Boost 1.81. Fixes https://github.com/moves-rwth/storm/issues/320.
> Workaround for issue with Boost Phoenix 1.81

- src/storm/transformer/SubsystemBuilder.cpp
This PR contains a small fix for the SubsystemBuilder. Previously, if a non-deterministic model had a transition reward matrix and a subsystem was created where the rowgrouping is trivial, this was not carried over to the transition reward matrix, leading to failed assertions.
> Fixed transitionRewardMatrix transformation in SubsystemBuilder

- src/storm-dft/parser/DFTJsonParser.cpp
Fix: the `DFTJsonParser` set elements as relevant even if the entry was set to `false`
> Storm-dft: check if element is relevant

- _layouts/home.html
- documentation/obtain-storm/apple-silicon.md
- documentation/obtain-storm/build.md
- documentation/obtain-storm/dependencies.md
I generally tried to reduce statements like `we require at least version x.y of library Z`.
In most cases, its hard to maintain and test those statements and I'm sure at least some of them were quite outdated.
Also, any Ubuntu, Debian, or macOS systems that has been updated within the last two years should be fine, so these kind of statements are not as relevant as they were a couple of years ago.
> Website: Update home and build instructions

- src/storm/models/sparse/StandardRewardModel.h
- src/storm/utility/solver.cpp
- src/test/storm/solver/LpSolverTest.cpp
In 99% of cases, z3 should be present anyway, but at least it should compile without it as well.
> Fixed compilation if Z3 is not present

- .clang-format
- .github/workflows/formatapply.yml
- .github/workflows/formatcheck.yml
- use latest version of the [clang-format-lint action](https://github.com/marketplace/actions/clang-format-lint)
- updated C++ standard used by clang-format to C++17
> Update clang-format actions to version 16

- resources/3rdparty/modernjson/src/basic_json_forward.h
- src/storm-cli-utilities/cli.h
- src/storm-gspn/builder/ExplicitGspnModelBuilder.cpp
- src/storm-gspn/builder/ExplicitGspnModelBuilder.h
- src/storm/exceptions/ExceptionMacros.h
- src/storm/logic/RewardAccumulation.h
- src/storm/modelchecker/prctl/helper/rewardbounded/EpochManager.h
- src/storm/storage/jani/traverser/InformationCollector.h
- src/storm/utility/NumberTraits.h
- src/storm/utility/string.h
Added `#include <cstdint>` to the following files:
- src/storm/logic/RewardAccumulation.h
- src/storm/modelchecker/prctl/helper/rewardbounded/EpochManager.h
- src/storm/utility/NumberTraits.h
- src/storm/storage/jani/traverser/InformationCollector.h
- src/storm/utility/string.h
- src/storm-cli-utilities/cli.h
I am not sure why, but the omission of this include caused errors on the latest versions of both GCC and Clang on Artix Linux.
Tested with the following C++ compilers
gcc (GCC) 13.1.1 20230429
clang version 15.0.7
CMake version:
cmake version 3.26.3
> Added `#include <cstdint>` to some files

- .github/workflows/buildtest.yml
Adds compiler tests to the CI: building Storm with GCC and Clang on Archlinux. Using Archlinux as OS allows to use the most recent compiler versions.
Note that the tests will currently fail. These compile issues should be fixed by https://github.com/moves-rwth/storm/pull/368.
> CI tests with different compilers

- .github/workflows/formatapply.yml
- .github/workflows/formatcheck.yml
Clang-format 16.0.0 caused some whitespace issues (see https://github.com/llvm/llvm-project/issues/62161). This PR updates the CI action to  which now uses clang-format in version 16.0.3.
Some formatting introduced with https://github.com/moves-rwth/storm/pull/370 will be reverted after we apply the auto-format.
> Use latest clang-format version in CI

- .clang-format-ignore
This adds Storm-POMDP as a target for formatting.
> Add Storm-POMDP to auto-formatting

- src/storm-pomdp/analysis/WinningRegion.h
After applying the formatting, for some reason WinningRegion.h is missing the declaration of storm::expressions::Expression which prevents compilation.
This fixes the issue. Thanks to @volkm for bringing this to my attention.
> Fix missing declaration

- .github/workflows/formatapply.yml
The auto-format CI action does not automatically trigger the CI checks. This is intended behaviour by Github, see [here](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow). Following the possible workarounds listed [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs), I suggest to use the simplest one: just inform the developer to manually close and open the PR.
> Provide guidance how to trigger CI in auto-format PR

- CHANGELOG.md
- resources/3rdparty/CMakeLists.txt
- previous fix (#321) was limited to only version 1.81.
- fixes https://github.com/moves-rwth/homebrew-storm/issues/8
- Boost version comparison is a bit complicated because the value of `Boost_VERSION` [changes starting with CMake version 3.15](https://cmake.org/cmake/help/latest/policy/CMP0093.html#policy:CMP0093)
> Extended fix of PR#321 to all Boost version >= 1.81

- src/storm-pomdp/api/verification.h
- src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.cpp
- src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.h
This PR contains small changes to Storm-POMDP that are necessary to make the python bindings in stormpy work.
> Changes in Storm-POMDP for stormpy to work

- documentation/obtain-storm/build.md
- getting-started.md
- `stormchecker` package on AUR is working again
- Added information which method of Storm installation is supported per OS
> Website: updated information for AUR on Arch Linux

- .github/workflows/Dockerfile.archlinux
- .github/workflows/Dockerfile.carl_implicit
- Dockerfile
Rolling release of Archlinux requires updates in the Dockerfile to prevent issues based on partial updates such as [this](https://github.com/moves-rwth/storm/actions/runs/5759073389/job/15612569262).
> CI: force update in Archlinux Dockerfile

- src/test/storm-pomdp/modelchecker/BeliefExplorationPomdpModelCheckerTest.cpp
Add check to only compile clipping tests if Z3 is installed.
Fixes #408
> Add check to only compile clipping tests if Z3 is installed

- src/storm/generator/JaniNextStateGenerator.cpp
- src/storm/generator/NextStateGenerator.cpp
- src/storm/generator/NextStateGenerator.h
- src/storm/generator/PrismNextStateGenerator.cpp
Raised in https://github.com/moves-rwth/stormpy/issues/136.
The issue was that initially an empty `VariableInformation` was created and only later replaced by the complete one in the `NextStateGenerator`. As a result information about out-of-bounds values was not considered. I fixed it by adding a new method `initializeSpecialStates` which needs to be explicitly called after creating the VariableInformation.
> Fixed issue with out-of-bounds flag

- .github/workflows/buildtest.yml
Explicitly set `STORM_VERSION_COMMITS_AHEAD` in `version.cmake`. This ensures that the Storm version is correctly set in the Docker container even though no git information is available.
Also updated some Github actions to the latest version.
> CI: explicitly set STORM_VERSION_COMMITS_AHEAD

- src/storm/adapters/JsonAdapter.h
- src/storm/adapters/JsonForward.h
- src/storm/api/export.h
Three occurrences of the json adapter in a header remain (notice that this is bad for compile times).
> remove one more header include of JsonAdapter

- src/storm/storage/prism/OverlappingGuardAnalyser.cpp
TQ rightfully pointed out that this should not be part of the huge interval commit..
Regarding content: The conjunction is not defined on empty sets. This fixes the issue.
> bugfix in overlapping guards analysis

- src/storm/generator/PrismNextStateGenerator.cpp
- src/storm/storage/prism/Constant.cpp
- src/storm/storage/prism/Constant.h
- src/storm/storage/prism/Program.cpp
- src/storm/storage/prism/Program.h
- src/storm/storage/prism/ToJaniConverter.cpp
- Initial construct does not need to be exposed to the outside world. Makes the API tiny bit easier.
- Comparing two constants is helpful 
- Erase & Remove idiom correctly applied
- Updating initial state expression is helpful for programmatically changing the initial state.
> prism program ops improvements and potential to update initial states

- src/test/storm-pomdp/api/BeliefExplorationAPITest.cpp
> Fixed warnings for comparisons in tests

- src/storm-dft/transformations/SftToBddTransformator.h
- src/storm-pomdp/api/verification.h
- src/test/storm-pomdp/api/BeliefExplorationAPITest.cpp
- src/test/storm-pomdp/modelchecker/BeliefExplorationPomdpModelCheckerTest.cpp
- src/test/storm/modelchecker/prctl/mdp/RobustMdpPrctlModelCheckerTest.cpp
Tests should build without warnings in the CI.
- removed hard-coded path and formula in `RobustMdpPrctlModelCheckerTest`
- removed `env` parameter in POMDP modelchecker which is unused
> Removed warnings in tests

- CMakeLists.txt
I wanted to re-enable the allwarnings on my machine and that was such a mess that I disabled many of them for now. Hope it makes this useful again.
> disable all kind of warnings when setting clang-allwarnings

- resources/examples/testfiles/imdp/tiny-05.drn
- src/storm/modelchecker/prctl/helper/SparseMdpPrctlHelper.cpp
- src/test/storm/modelchecker/prctl/mdp/RobustMdpPrctlModelCheckerTest.cpp
For interval models, the model checking result actually contains values for every state. So we do not need to merge it with the qualitative state results.
> interval model checking fix for postprocessing results

- src/storm/modelchecker/helper/indefinitehorizon/visitingtimes/SparseDeterministicVisitingTimesHelper.cpp
STORM_PRINT produces unwanted messages when computing expected visits multiple times, and (as far as I know) cannot be disabled.
> replace print with logging when computing expected visits

- src/storm/solver/helper/ValueIterationOperator.h
This PR contains small adjustments to robust VI that significantly speed up the computations (at least 10x). Profiling revealed that re-allocating the vector is costly (already pointed out by the comment) and `diameter()` changes the rounding mode on each call, which is very expensive. I could not manage to get faster sorting than `std::sort`, although I haven't tried using `boost::container::flatmap`. I will try that in a private branch later :) for now it's a good improvement.
> Optimization of robust VI

- src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.cpp
This PR removes a line that always sets the threshold for the size of the belief MDP to the heuristic value computed by Storm if it is not explicitly set different from the default.
The intended behaviour is for the belief exploration to ignore the size threshold if a time limit for the belief exploration and no explicit size threshold are given.
> Fixed wrong size threshold if exploration time limit is given

- resources/3rdparty/CMakeLists.txt
Recently, CI builds fail because they are sometimes stuck in obtaining the z3 version. See [here](https://github.com/moves-rwth/storm/actions/runs/8305864391/job/22738791859#step:3:200) for an example.
The problem might be due to compiling a small program with z3 in order to obtain the z3 version.
This PR obtains the z3 version by parsing the file `z3_version.h` instead. The old option is still present to preserve backwards compatibility to versions before [this fix](https://github.com/Z3Prover/z3/issues/1833).
> Get z3 version by parsing version file

- src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.cpp
Removes two "unused variable" warnings in beliefExplorationPomdpModelChecker
> Remove Warnings

- src/storm-cli-utilities/model-handling.h
- src/storm-gspn/storage/gspn/GSPN.cpp
- src/storm-pars-cli/feasibility.cpp
- src/storm-pars-cli/print.cpp
- src/storm-pomdp-cli/storm-pomdp.cpp
- src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.cpp
- src/storm/utility/macros.h
Adds wrapping `do{...} while` to STORM_PRINT and STORM_PRINT_AND_LOG macro definitions to require their uses to be followed by a semicolon. Also adjusts occurences where previously the semicolon was not present.
Resolves #551
> Modify printing macros to require a trailing semicolon

- .github/workflows/Dockerfile.archlinux
- .github/workflows/buildtest.yml
- Dockerfile
Allow to enable/disable several libraries/configs in the Dockerfile.
Also adapted the CI build configs to the new Dockerfile.
> Added configuration options to Dockerfile

- src/storm/generator/NextStateGenerator.cpp
```
./bin/storm --prism ../resources/examples/testfiles/dtmc/die.pm --state-limit 5
```
now introduces the `unexplored` label
```
-------------------------------------------------------------- 
Model type: 	DTMC (sparse)
States: 	5
Transitions: 	7
Reward Models:  none
State Labels: 	3 labels
* unexplored -> 3 item(s)
* deadlock -> 0 item(s)
* init -> 1 item(s)
Choice Labels: 	none
-------------------------------------------------------------- 
```
while the invocation without a state limit does not:
```
./bin/storm --prism ../resources/examples/testfiles/dtmc/die.pm                
```
```
-------------------------------------------------------------- 
Model type: 	DTMC (sparse)
States: 	13
Transitions: 	20
Reward Models:  none
State Labels: 	2 labels
* deadlock -> 0 item(s)
* init -> 1 …
```
> Fix always introducing the unexplored label. Fixes #559.

- src/storm/modelchecker/prctl/helper/SparseMdpPrctlHelper.cpp
- src/storm/storage/SparseMatrix.cpp
~This PR tracks bughunting for a bug~
Fixes the initial policy computation. The previous implementation did not correctly handle choices to states with infinite reward.
> Fix policy iteration for minimal reach reward properties

- src/storm-parsers/api/properties.cpp
The parseProperties function taking only a string as input is not able to parse properties containing model variables as these are not registered with the created ExpressionManager.
This is expected behaviour, however, the resulting error message of the form
```
ERROR (SpiritErrorHandler.h:27): Parsing error at 1:2:  expecting <basic path formula>, here:
X (var = 0)]
^
```
does not point to the actual problem, making debugging the issue difficult, in particular for inexperienced users.
This PR adds a warning to the function that makes the issue more apparent.
Thanks to @SvStein for bringing this to my attention.
> Add warning in API concerning properties containing model variables

- src/storm-dft/modelchecker/DFTModelChecker.cpp
- src/storm/utility/initialize.cpp
- src/storm/utility/initialize.h
- The DFTModelChecker specified its own precision instead of following the default.
- Made `setOutputDigits` private.
> Follow general output precision in DFT approximation

- .github/workflows/buildtest.yml
- .github/workflows/doxygen.yml
- .github/workflows/release_docker.yml
- doc/offline_package.md
Increased number of Github runners from 2 to 4. Leads to faster CI runs (see [old](https://github.com/moves-rwth/storm/actions/runs/10026195486/usage) and [new](https://github.com/volkm/storm/actions/runs/10056576731/usage) timings).
> Use 4 threads in CI

- .github/workflows/buildtest.yml
- CMakeLists.txt
- src/storm/modelchecker/multiobjective/preprocessing/SparseMultiObjectiveRewardAnalysis.cpp
- src/storm/modelchecker/results/ExplicitQualitativeCheckResult.cpp
- src/storm/modelchecker/results/ExplicitQualitativeCheckResult.h
- src/storm/modelchecker/results/ExplicitQuantitativeCheckResult.cpp
- src/storm/modelchecker/results/ExplicitQuantitativeCheckResult.h
- Use C++20 and fixed some includes (resolves #286)
- Bump CMake to 3.22
- Removed support for Debian 11 and Ubuntu 20.04
- Regularly enable CLN and Ginac again for Apple Silicon
> Bump build system

- src/storm/settings/modules/SylvanSettings.cpp
- src/storm/utility/OsDetection.h
Follows the suggestion in https://github.com/moves-rwth/storm/issues/600.
Workaround for https://github.com/moves-rwth/storm/issues/523.
> Limit Sylvan threads to 1 on Apple Silicon

- resources/examples/testfiles/dft/modules3.dft
- src/storm-dft/storage/DFT.cpp
- src/test/storm-dft/api/DftModelCheckerTest.cpp
Representants were not properly updated when the element was part of a spare module but also of the top module.
Also added a test case triggering this issue.
> Fixed issues with DFT representant computation

- src/storm/simulator/PrismProgramSimulator.cpp
- src/storm/storage/BitVectorHashMap.h
Should prevent the issue raised in https://github.com/moves-rwth/storm/issues/607 in the future.
> Require explicitly providing bucketSize for BitVectorHashMap

- src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.cpp
- src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.h
Read more information here: https://github.com/moves-rwth/stormpy/pull/185
In short, pybind11 can cause problems while exposing smart pointer objects. With this change we don't need to access the BeliefMdpExplorer object via the function getInteractiveBeliefExplorer anymore, as the only functionality we needed in that object (that is the setFMSchedValueList function) is being exposed into the BeliefExplorationPomdpModelChecker class.
> Part of a fix for a double free issue in StormPy

- src/storm/storage/BitVector.cpp
- src/storm/storage/BitVector.h
The BitVector iterators weren't default-construtable and were missing postfix increment operators and thus not fulfilling the range concept (https://en.cppreference.com/w/cpp/ranges/range). Changing this makes it possible to use BitVector with C++20s range adaptors. E.g. for code like this:
```c++
for (auto i : some_bitvector | std::views::filter(some_lambda)) {
do_something(i);
}
```
> Made BitVector conform to the std::ranges::range concept

- src/storm-pars/analysis/OrderExtender.cpp
1.  Bug: Not all states were added to the order properly when using PLA bounds. They were simply set to done when all their successors could be ordered via PLA bounds, but not put into the order. They were at best only added trivially (between top and bottom) when required later as another state's successor. These states are now no longer set to done so that the main loop will still consider them and integrate them into the order properly.
2. Bug: The zeroconf benchmark only resulted in no increasing parameter (with PLA) or one increasing parameter (without PLA), whereas the correct (and previously attained) result is that both parameters are increasing. The order was correct and did lend itself to concluding the correct result but local monotonicity was not checked at all states, …
> Two Monotonicity Bugfixes

- resources/3rdparty/CMakeLists.txt
Fixes #616 
`git apply --reverse --check` checks if the patch was already applied (by trying to reverse it) and otherwise applies the patch.
> Check if Eigen patch was already applied

- src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.cpp
Changes output in BeliefExplorationPomdpModelChecker to prevent unwanted printing when functions are used in stormpy.
Resolves #648
> Change printing behavior in belief exploration

- src/storm/storage/prism/Program.cpp
- src/storm/storage/prism/Program.h
- src/storm/storage/sparse/StateValuations.cpp
- src/storm/storage/sparse/StateValuations.h
* `prism::Program::getAllExpressionVariables` now has the possibility to not include constants
* added `storage::sparse::StateValuations::getIntegerValues()` and similar for other types, to provide access to all state values of a given variable
> Added two functions for more convenient access to state valuations

- src/storm/modelchecker/helper/ltl/SparseLTLHelper.cpp
- src/storm/modelchecker/helper/ltl/internal/SparseLTLSchedulerHelper.cpp
- src/storm/modelchecker/helper/ltl/internal/SparseLTLSchedulerHelper.h
- src/storm/storage/MaximalEndComponentDecomposition.cpp
I streamlined the decomposition into MECs by preventing to iterate over all remaining candidates for every end component and by keeping track of MECs that contain an accepting end component
> Speed up of MEC decomposition by adjusting loops

- resources/examples/testfiles/dft/fdep7.dft
- resources/examples/testfiles/dft/spare_contains_spare.dft
- src/storm-dft-cli/storm-dft.cpp
- src/storm-dft/api/storm-dft.h
- src/storm-dft/parser/DFTGalileoParser.cpp
- src/storm-dft/parser/DFTJsonParser.cpp
- src/storm-dft/storage/DFT.cpp
- src/storm-dft/storage/DFTState.cpp
- src/storm-dft/utility/DftValidator.cpp
- src/storm-dft/utility/DftValidator.h
- src/test/storm-dft/api/DftModelCheckerTest.cpp
- src/test/storm-dft/api/DftValidatorTest.cpp
- src/test/storm-dft/simulator/DftSimulatorTest.cpp
- src/test/storm-dft/storage/SymmetryTest.cpp
Added a separate function to check for potential modeling issues in DFT. These issues do not prevent analysis but might lead to unexpected results.
We consider two potential issues for now:
- spare modules which are initially activated because they overlap with the top module
- We allow that elements in the primary module of a SPARE gate are also connected to other parts of the fault tree. In an edge case, this can lead to unexpected behavior though, if the SPARE parent is also part of the spare module but not directly connected to the top module. In this instance, the SPARE is never activated.
> Warning on potential modeling issues in DFT

- .github/workflows/buildtest.yml
- CMakeLists.txt
- Xcode 14.3 on macOS 13 (Intel)
- Xcode 15.4 on macOS 14 (ARM)
- Xcode 16.2 on macOS 15 (ARM)
(The CI also shows that the ARM processors nearly halve the compilation times.)
- AppleClang needs at least Xcode version 14.3. XCode version 14.2 fails, see [this test](https://github.com/volkm/storm/actions/runs/13721879189/job/38378974632). Fixes #684
- Bumped Clang and GCC versions to the first versions supporting the flag ` -std=c++20`. The required compiler versions are probably still too low. But I did not want to run extensive tests as the CMake version is most likely the main restriction at the moment anyway.
- AppleClang 14 [still failed with the checks](https://github.com/volkm/storm/actions/runs/13724840840/job/38388686191).
> Support for macOS builds in CI

- src/storm-pomdp/modelchecker/BeliefExplorationPomdpModelChecker.cpp
This PR extends the labeling for induced Markov chains of belief MDPs with an indication which node of an FSC is used for cut-offs when external cut-off values are provided.
This is in particular important for obtaining the scheduler from the belief exploration, e.g. in the context of SAYNT.
Resolves #688
> Add cut-off memory node information

- resources/examples/testfiles/pomdp/maze2_sl0.drn
- src/storm-parsers/parser/DirectEncodingParser.cpp
- src/test/storm/parser/DirectEncodingParserTest.cpp
The DRN parser had the order of observations and state rewards switched up compared to the exporter.
Furthermore, whitespaces were not properly handled in the observation parsing part.
Also added a test case for the explicit parsing of POMDPs.
Fixes #689
> Fix DRN POMDP parsing

- src/storm-dft/transformations/DftInstantiator.h
- src/storm-pars/derivative/SparseDerivativeInstantiationModelChecker.cpp
- src/storm-pars/transformer/ParameterLifter.cpp
- src/storm-pars/utility/ModelInstantiator.h
- src/storm-pars/utility/parametric.cpp
- src/storm-pars/utility/parametric.h
- src/test/storm-pars/derivative/SparseDerivativeInstantiationModelCheckerTest.cpp
- src/test/storm-pars/modelchecker/SymbolicParametricDtmcPrctlModelCheckerTest.cpp
Added automatic conversion to the desired return type in `parametric::evaluate`. This allows to replace the common construct
```
storm::utility::convertNumber<ConstantType>(storm::utility::parametric::evaluate(function, valuation));
```
by the simpler version
```
storm::utility::parametric::evaluate<ConstantType>(function, valuation);
```
If the types are equal, then of course no conversion is performed.
Drawback is that the include `constants.h` is now moved to the header file `parametric.h` but I think this is acceptable.
> Support conversion in function parametric::evaluate

- resources/3rdparty/include_spot.cmake
[Changes](https://gitlab.lre.epita.fr/spot/spot/blob/spot-2-14-1/NEWS) should be irrelevant for us.
> Bumped Spot to version 2.14.1

- src/storm-dft/parser/DFTJsonParser.cpp
Otherwise trying to add the layout information in the next step will fail.
> Skip PDEP with probability 0 during parsing

- src/storm/solver/GurobiLpSolver.cpp
- src/storm/solver/GurobiLpSolver.h
This PR adds the possibility to specify a time limit when using the Gurobi LP solver. This allows for stopping the solver before an optimal solution is found and retrieving sub-optimal solutions.
The following changes have been made:
- The following methods have been added to `GurobiLpSolver`: 
* `setTimeLimit(uint64_t seconds)`: sets the parameter in the underlying Gurobi environment of the model
* `hasTimeLimit()`: returns whether a time limit has been set
* `getTimeLimit()`: returns the time limit if it has been set, otherwise an `InvalidAccessException` is thrown
* `hasTimedOut()`: returns whether a time out has occurred (implemented analogously to the check of optimality)
- The methods for retrieving sub-optimal solutions have been adapted, i.e. `getContinuousValue(...)`, …
> Time limit for Gurobi LP Solver

- .github/workflows/release.yml
- doc/checklist_new_release.md
After a release of Storm, the CI triggers a PR which again adds the suffix `.1` to the Storm version to indicate the next development version.
> CI: set development version of Storm after release
